stages:
  - stage: A
    jobs:
      - job: Debug
        steps:
          - bash: echo "Hello from debug"
      - job: Release
        dependsOn: Debug
        steps:
          - bash: echo "Hello from Relase"
  - stage: B
    jobs:
      - job: B1
      - job: B2