stages:
  - stage: A
    jobs:
      - job: Debug
        steps:
          - bash: echo "Hello from debug"
      - job: Release
        dependsOn: Debug
        steps:
          - bash: echo "Hello from Relase"
  - stage: B
    jobs:
      - job: Windows
        pool:
          vmImage: 'vs2017-win2016'
        steps:
        - script: echo hello from Windows
      - job: macOS
        pool:
           vmImage: 'macOS-10.14'
        steps:
        - script: echo hello from macOS
      - job: Linux
        pool:
            vmImage: 'ubuntu-16.04'
        steps:
        - script: echo hello from Linux
  - stage: C
    jobs:
      - job: MultiJob
        strategy:
         maxParallel: 2
         matrix: 
          US_IE:
           Location: US
           Browser: IE
          US_Chrome:
           Location: US
           Browser: Chrome
          Europe_Chrome:
           Location: Europe
           Browser: Chrome 
